version: 2
updates:
  - package-ecosystem: npm
    directory: "/nodejs/benchmark"
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ["*"]
      npm-security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: docker
    directory: "/docker/ubuntu-latest"
    schedule:
      interval: weekly
    groups:
      docker:
        patterns: ["*"]
      docker-security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: docker-compose
    directory: "/"
    schedule:
      interval: weekly
    groups:
      docker-compose:
        patterns: ["*"]
      docker-compose-security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
      github-actions-security:
        applies-to: security-updates
        patterns: ["*"]
